### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by harshalkd** [zoho/Desk-androidSampleApp#2]
Hi team ,
I recently try SDK code in android project but when i run it i got error like below 

     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at java.net.URLEncoder.encode(URLEncoder.java:204)
        at com.zoho.accounts.externalframework.Util.encode(Util.java:39)
        at com.zoho.accounts.externalframework.ZohoSDK.getClientID(ZohoSDK.java:264)
        at com.zoho.accounts.externalframework.URLUtil.getIAMOAuthURL(URLUtil.java:23)
        at com.zoho.accounts.externalframework.ZohoSDK.presentLoginScreen(ZohoSDK.java:73)
        at com.zoho.accounts.externalframework.ZohoSDK.presentLoginScreen(ZohoSDK.java:64)
        at com.example.zohosdk.WelcomeActivity.onCreate(WelcomeActivity.java:31)
        at android.app.Activity.performCreate(Activity.java:6984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
any idea what is wrong on this?

**Comment by Rey272871** [comment]
I can't login to pojav launcher

**Comment by neelamchauhan33551** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.net.URLEncoder.encode(URLEncoder.java:224)
	at java.net.URLEncoder.encode(URLEncoder.java:196)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.convertToFormData(MicrosoftBackgroundLogin.java:336)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:129)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$0$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda0.call(Unknown Source:6)
	at com.movtery.zalithlauncher.task.SimpleTask.performMainTask(SimpleTask.kt:7)
	at com.movtery.zalithlauncher.task.Task.execute$lambda$7(Task.kt:108)
	at com.movtery.zalithlauncher.task.Task.$r8$lambda$slCHU1ZCBTw2VF3M7tx5-t6MzUc(Unknown Source:0)
	at com.movtery.zalithlauncher.task.Task$$ExternalSyntheticLambda2.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
	at java.lang.Thread.run(Thread.java:1119)

**Comment by neelamchauhan33551** [comment]
How to fix

**Comment by balasubramanian-k-19828** [comment]
We offer two different SDKs for Zoho Desk, each designed for a specific use case:

1. ASAP SDK (Help Center for End-Users)
If the customer needs to provide Zoho Desk’s Help Center features to their end-users within their own application, the ASAP (Customer Portal) SDK is the right choice.
- [ASAP SDK Documentation](https://help.zoho.com/portal/en/kb/desk/developer-space/asap)
- [iOS Code Sample](https://github.com/zoho/ZohoDesk-PortalSDK-Sample-apps-iOS)
- [Android Code Sample](https://github.com/zoho/ZohoDesk-PortalSDK-sample-apps-android)

2. Desk SDK (For Agents)
If the requirement is to build a customized Desk app for their internal support agents, they should use the Desk SDK.
- i[OS Desk SDK Documentation](https://www.zoho.com/desk/developers/mobilesdk/ios/)
- [Android Desk SDK Documentation](https://www.zoho.com/desk/developers/mobilesdk/android/)
- [iOS Desk SDK Sample App](https://github.com/zoho/Desk-iOSSampleApp)
- [Android Desk SDK Sample App](https://github.com/zoho/Desk-androidSampleApp)

If they have any further questions or need implementation assistance, please ask them to reach out to support@zohodesk.com
 with as much detail as possible.
